O.fursov homework 1
IT-Academy-Front-Team/Homeworks pull request #12
Opened 2022-02-19 14:21 UTC by OlegFursau

Homework-19

2022-02-19 14:48 UTC, OlegFursau commented
пофиксил минуты

2022-02-23 15:38 UTC, IT-Academy-Front-Team requested changes

2022-02-23 15:38 UTC, IT-Academy-Front-Team commented on Oleg_Fursov/homework-19/timer.css
> +body {
мы в нашем PR ни в коем случае не удаляем чужие папки и файлы, ридми тоже. это то же самое как если бы на реальном проекте вы бы взяли и удалили чужой кусок проекта

2022-02-23 15:38 UTC, IT-Academy-Front-Team commented on Oleg_Fursov/homework-19/timer.css
> +    box-shadow: 0px 2px 0px blue;
0 пишется без единиц - везде поправить

2022-02-23 15:38 UTC, IT-Academy-Front-Team commented on Oleg_Fursov/homework-19/timer.html
> +
отступ огромный лишний

2022-02-23 15:38 UTC, IT-Academy-Front-Team commented on Oleg_Fursov/homework-19/timer.js
> +//* на каждой итерации и считать их до 100.
- не должно быть перезагрузки страницы по клику на ресет когда таймер дошел до конца и вообще по клику на ресет
- блок для меток когда он пустой можно спрятать

2022-02-23 20:06 UTC, OlegFursau commented on Oleg_Fursov/homework-19/timer.html
> +
fix

2022-02-23 20:07 UTC, OlegFursau commented on Oleg_Fursov/homework-19/timer.css
> +body {
fix

2022-02-25 17:02 UTC, IT-Academy-Front-Team approved these changes

2022-02-25 17:02 UTC, merged