Katsiaryna Tabunova - Homework 17-18
IT-Academy-Front-Team/Homeworks pull request #13
Opened 2022-06-20 08:11 UTC by KatsiarynaTabunova

2022-06-29 13:02 UTC, IT-Academy-Front-Team requested changes

2022-06-29 13:02 UTC, IT-Academy-Front-Team commented on Katsiaryna_Tabunova/Homework-17-18/script.js
> +                    number2 = number1;
здесь можно деструкт заюзать

2022-06-29 13:02 UTC, IT-Academy-Front-Team commented on Katsiaryna_Tabunova/Homework-17-18/script.js
> +        .then((currentNumber) => {
1 парам не оборачиваем в скобки

2022-07-03 10:14 UTC, AlesyaLobatch approved these changes

2022-07-03 10:14 UTC, AlesyaLobatch commented on Katsiaryna_Tabunova/Homework-17-18/script.js
> +        return arr.map(name => ({[`Пользователь ${++i}`]: name})
а i то у вас откуда возьмется)

2022-07-03 10:14 UTC, AlesyaLobatch commented on Katsiaryna_Tabunova/Homework-17-18/script.js
> +        return arr.reduce((acc, item) => Object.assign({}, acc, item))
у вас каждый раз будет создаваться новый объект. он должен создаваться 1 раз, в изнач параметре редьюс

2022-07-03 10:15 UTC, IT-Academy-Front-Team approved these changes

2022-07-03 10:16 UTC, merged