Dmitry Gorodko - Homework 20
IT-Academy-Front-Team/Homeworks pull request #19
Opened 2021-01-20 19:14 UTC by Amatid

Homework 20 is done completely

2021-02-01 21:54 UTC, IT-Academy-Front-Team requested changes
- неверно ответвились
- неверное поведение по окончании  работы таймера и соотв. при перезагрузке в этот момент

2021-02-18 14:48 UTC, AlesyaLobatch submitted a review, later dismissed

2021-02-18 14:49 UTC, IT-Academy-Front-Team approved these changes

2021-02-18 14:49 UTC, IT-Academy-Front-Team approved these changes

2021-02-18 14:49 UTC, merged