Lazarev_Aleksandr Homework-18
IT-Academy-Front-Team/Homeworks pull request #19
Opened 2021-06-04 20:59 UTC by gern132

add homework

2021-06-07 13:56 UTC, AlesyaLobatch requested changes

2021-06-07 13:56 UTC, AlesyaLobatch commented on Lazarev_Aleksandr/Homework_18/script.js
> +    console.log(/[a-zA-z]{3,10}[_]{1}[a-zA-z]{3,10}(-\w{4})?@[^(\.|\-)]+([A-Za-z0-9]{1}(\.|\-)?){1,2}[^(\.|\-)].com$/.test('name_surname-1234@gmail.com'));
- имя PR не по формату
- вместо прописывания и больших и маленьких букв лучше использовать флаг регистра
- [_]{1} если есть что-то, что захардкожено - т.е. юзается 1 раз - то скобки и {1} не нужно - поправьте везде
- \w посмотрите что входит в данное сокращение
- почтовый сервис реализован неверно. надо чтоб букв и цифр было от 1 до 10, затем опциональное тире или точка, и снова буквы и тире от 1 до 10

2021-06-07 13:56 UTC, AlesyaLobatch commented on Lazarev_Aleksandr/Homework_18/script.js
> +    var res = new RegExp('^\\+?(375|8)\\-?0?(25|29|33|44|17)[\\-]?[^0]\\d{2}[\\-]?\\d{2}[\\-]?\\d{2}$')
- тире не надо экранировать
- могу поставить + перед 8
- могу поставить 0 после 375
- [^0] - это может быть вообще что угодно
- [\\-]?\\d{2} дублир. часть - можно сократить

2021-06-09 16:06 UTC, IT-Academy-Front-Team approved these changes

2021-06-09 16:06 UTC, merged