Practice
IT-Academy-Front-Team/Homeworks pull request #19
Opened 2020-09-14 18:09 UTC by spirid

2020-09-14 18:09 UTC, spirid commented
practice1-6

2020-09-16 10:53 UTC, AlesyaLobatch requested changes

2020-09-16 10:53 UTC, AlesyaLobatch commented on Dima_Spiridonov/Practice/practice1-6.js
> +//1
почему здесь хранятся файлы таймера?
неверное имя pr

2020-09-16 10:53 UTC, AlesyaLobatch commented on Dima_Spiridonov/Practice/practice1-6.js
> +	treeNumber({a: 2, b: 3});
обычные функции-обертки в стрелочные лучше не переводить - а если переводим то не забываем ставить конст

2020-09-16 10:53 UTC, AlesyaLobatch commented on Dima_Spiridonov/Practice/practice1-6.js
> +	let user = ['Dima',39];
то же самое по функции
не используем деструктуризацию, принять надо как 2 отд. параметра

2020-09-16 10:53 UTC, AlesyaLobatch commented on Dima_Spiridonov/Practice/practice1-6.js
> +		for (let item of mass) {
невнимательно читаете условие. при вызове числа надо передать отдельно.
и то же самое по функции обертке

2020-09-16 10:53 UTC, AlesyaLobatch commented on Dima_Spiridonov/Practice/practice1-6.js
> +	vowelLetters.forEach(function (letter) {
тут стрелочная

решение длинное. можно в одну строку сделать. и метод includes заюзать. суть задания должна быть сохранена

2020-09-16 10:53 UTC, AlesyaLobatch commented on Dima_Spiridonov/Practice/practice1-6.js
> +countVowelLetters = text =>  {
функция-обертка

2020-09-23 11:15 UTC, closed without merging