Vitaly_Radiononv_Homework-1
IT-Academy-Front-Team/Homeworks pull request #2
Opened 2021-10-11 10:10 UTC by VitalyRadionov

Add homework

2021-10-11 10:21 UTC, VitalyRadionov commented on Vitaly_Radionov/lesson-19/asd.txt
> +good
чего-то не хватает

2021-11-01 11:43 UTC, IT-Academy-Front-Team requested changes
Глобально итог такой:
- во-первых мы каждую ДЗ пушим в отдельную ветку и отд ПР
- по секундомеру незачет
- ес6 правим

2021-11-01 11:43 UTC, IT-Academy-Front-Team commented on Vitaly_Radionov/homework_1/stopwatch/index.html
> +      <div class="minutes">00</div>
- есть переменные без лет
- функциональность с локал стораджем недоработана
- как такого работающего секундомера я не вижу - он доходит до 10 секунд и замирает

2021-11-01 18:43 UTC, VitalyRadionov commented on Vitaly_Radionov/homework_1/main.js
> +  a: a,
VS сам ставит отступы и пробелы, иногда не там где нужно(

2021-11-04 18:06 UTC, IT-Academy-Front-Team approved these changes

2021-11-04 18:06 UTC, merged