E.Zaprivarin_Homework 15
IT-Academy-Front-Team/Homeworks pull request #24
Opened 2022-06-21 21:45 UTC by EgorZaprivarin

2022-06-29 14:37 UTC, AlesyaLobatch requested changes

2022-06-29 14:40 UTC, AlesyaLobatch requested changes

2022-06-29 14:40 UTC, AlesyaLobatch commented on Egor_Zaprivarin/Homework-15/main.js
> +   return obj;
- для каждой дз новый ПР
- логика с налл не нужна
- содержимое перебир методов пишем в 1 строку без ретурн и фиг скобок

2022-06-29 14:40 UTC, AlesyaLobatch commented on Egor_Zaprivarin/Homework-15/main.js
> +
то же что и выше

2022-06-29 14:40 UTC, AlesyaLobatch commented on Egor_Zaprivarin/Homework-15/main.js
> +   }, {});
то же что и выше

2022-06-29 14:40 UTC, AlesyaLobatch commented on Egor_Zaprivarin/Homework-15/main.js
> +      return this._foodAmount + ' гр.';
избавляемся везде от конкатенации

2022-06-29 14:40 UTC, AlesyaLobatch commented on Egor_Zaprivarin/Homework-15/main.js
> +   .then(() => console.log('Промис завершён успешно'))
вот тут выводим посл запомненное число

2022-07-03 10:20 UTC, IT-Academy-Front-Team approved these changes

2022-07-03 10:20 UTC, merged