Homework 14
IT-Academy-Front-Team/Homeworks pull request #33
Opened 2021-06-07 06:37 UTC by AlexSyrtsev

Add Homework

2021-06-07 13:53 UTC, AlesyaLobatch requested changes

2021-06-07 13:53 UTC, AlesyaLobatch commented on Aleksei_Syrtsev/Homework-14/fd-2-syrtsev-homework14.js
> +console.log(/^[A-Za-z]{3,10}[_]{1}[A-Za-z]{3,10}(-[0-9]{4}){0,1}[@]{1}[a-zA-Z0-9]{1,10}[\.-]{0,1}[a-zA-Z0-9]{1,10}[\.]{1}com{1}$/.test(email));
- имя PR не по формату
- вместо прописывания и больших и маленьких букв лучше использовать флаг регистра
- [_]{1} если есть что-то, что захардкожено - т.е. юзается 1 раз - то скобки и {1} не нужно - поправьте везде
- [0-9] можно сократить - поправьте везде
- {0,1} можно сократить - поправьте везде

2021-06-07 13:53 UTC, AlesyaLobatch commented on Aleksei_Syrtsev/Homework-14/fd-2-syrtsev-homework14.js
> +    var result = str.match(/[AEIOUYaeiouy]/g).length;
нет проверки на ситуацию, когда гласных 0

2021-06-07 13:53 UTC, AlesyaLobatch commented on Aleksei_Syrtsev/Homework-14/fd-2-syrtsev-homework14.js
> +    var pattern = /^[\+]{0,1}(375|8-0|80)[\-]{0,1}(17|25|29|33|44)[\-]{0,1}[1-9]{1}[0-9]{2}[\-]{0,1}[0-9]{2}[\-]{0,1}[0-9]{2}$/.test(thisNumber)
- могу поставить + перед 8
- могу поставить тире после 80-
- тире не надо экранировать
- {0,1}[0-9]{2} дублируется, можно сократить

2021-06-09 16:07 UTC, IT-Academy-Front-Team approved these changes

2021-06-09 16:07 UTC, merged