Aleksey Andreev - Homework 15
IT-Academy-Front-Team/Homeworks pull request #36
Opened 2022-08-29 23:37 UTC by ProStoFile

add homework

2022-08-29 23:39 UTC, ProStoFile commented
add homework

2022-09-06 15:09 UTC, IT-Academy-Front-Team requested changes
- кавычки
- сбросьте в лс видос как работает таймер когда доходит до конца - можно на значениях поменьше, метки должны сохраняться

2022-09-06 18:01 UTC, ProStoFile commented
Homework 15
fix bugs

2022-09-07 13:11 UTC, IT-Academy-Front-Team approved these changes

2022-09-07 13:11 UTC, merged